# zshrc 

bindkey -e

setopt auto_cd
setopt auto_pushd
setopt nolistbeep
setopt magic_equal_subst
setopt pushd_ignore_dups
setopt extended_glob
setopt complete_in_word

stty stop undef

# history
HISTFILE=~/.zsh_history
HISTSIZE=100000000
SAVEHIST=100000000
setopt hist_ignore_dups
setopt share_history
setopt hist_ignore_space

# auto complete
autoload -U compinit 
compinit

autoload -U colors
colors

# prompt
function is_in_chroot() {
    tmp=$(ls -id / | awk '{print $1}')
    if [ ${tmp} -eq 2 ]; then
        echo 0
    else 
        echo 1
    fi
}


# aliases
alias ls="ls --color=auto"
alias mkdir="mkdir -p"

# cdls
cd() {
    builtin cd "$@" && ls --color=auto
}


#  --- peco ---
#  history
function peco-history-selection() {
    BUFFER=`history -n 1 | tac | awk '!a[$0]++' | peco`
    CURSOR=$#BUFFER
#      zle accept-line
}
zle -N peco-history-selection

function peco-history-set-on-cursol()
{
    peco-history-selection
    zle reset-prompt
}
zle -N peco-history-set-on-cursol

function peco-history-execute()
{
    peco-history-selection
    zle accept-line
}
zle -N peco-history-execute

# process
function peco-kill-process () {
    ps -ef | peco | awk '{ print $2 }' | xargs kill
}

if which peco 2>/dev/null; then
    alias kill="peco-kill-process"
    bindkey '^r' peco-history-execute
    bindkey '^t' peco-history-set-on-cursol
fi


#  load external files
[ -f $HOME/.zshrc.mine ] && source $HOME/.zshrc.mine

# for tmux
if [ -z "$TMUXCLIENT" ]; then
    alias tmux="tmux -2"
else
    alias tmux='tmux -2 -f"$HOME/.tmux.conf.client"'
fi

if which tmux 2>/dev/null; then
    [[ -z "$TMUX" && ! -z "$PS1" ]] && tmux
fi

#  autoload
autoload -Uz vcs_info
setopt prompt_subst
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr "%F{yellow}!"
zstyle ':vcs_info:git:*' unstagedstr "%F{red}+"
zstyle ':vcs_info:*' formats "%F{green}%c%u[%b]%f"
zstyle ':vcs_info:*' actionformats '[%b|%a]'
precmd () { vcs_info }

if [ `is_in_chroot` -eq 0 ]; then
    PROMPT='${vcs_info_msg_0_} '"[%{${fg[cyan]}%}%n@%m%{${reset_color}%}]$ "
else 
    PROMPT="[%{${fg[blue]}%}%n@chroot%{${reset_color}%}]$ "
fi
RPROMPT="[%{${fg[cyan]}%}%~%{${reset_color}%}]"

function ls_func() {
    ls 
    zle reset-prompt  # プロンプトを再描画
 }
zle -N ls_func # my_functionをwidgetとして登録
bindkey '^O' ls_func # my_functionをCtrl-Aにバインド

function make_func () {
    make 
    zle reset-prompt  # プロンプトを再描画
 }
zle -N make_func  # my_functionをwidgetとして登録
bindkey '^V' make_func # my_functionをCtrl-Aにバインド

function lb() {
    vim ~/logbook/$(date '+%Y-%m-%d').md
}

eval "$(fasd --init zsh-hook)"

fasd_peco() {
    cd "$(fasd -s | awk '{print $2}' | peco)"
}
alias z=fasd_peco

tmux_attach() {
    tmux attach -t "$(tmux ls |peco | awk '{print substr($1, 0, 1)}')"
}
alias tattach=tmux_attach

