# zshrc 

bindkey -e

setopt auto_cd
setopt auto_pushd
setopt nolistbeep
setopt magic_equal_subst
setopt pushd_ignore_dups
setopt extended_glob
setopt complete_in_word

stty stop undef

# history
HISTFILE=~/.zsh_history
HISTSIZE=100000000
SAVEHIST=100000000
setopt hist_ignore_dups
setopt share_history
setopt hist_ignore_space

# auto complete
autoload -U compinit 
compinit

autoload -U colors
colors

# prompt
PROMPT="[%{${fg[cyan]}%}%n@%m%{${reset_color}%}]$ "
RPROMPT="[%{${fg[cyan]}%}%~%{${reset_color}%}]"

# for tmux
alias tmux="tmux -2"
if which tmux 2>/dev/null; then
    [[ -z "$TMUX" && ! -z "$PS1" ]] && tmux
fi

# aliases
alias ls="ls --color=auto"
alias mkdir="mkdir -p"

# cdls
cd() {
    builtin cd "$@" && ls --color=auto
}


#  --- peco ---
#  history
function peco-history-selection() {
    eval $(history -n 1 | tac | awk '!a[$0]++' | peco)
	zle reset-prompt
}


# process
function peco-kill-process () {
    ps -ef | peco | awk '{ print $2 }' | xargs kill
}

if which peco 2>/dev/null; then
    alias kill="peco-kill-process"
    zle -N peco-history-selection
    bindkey '^R' peco-history-selection
fi


#  load external files
[ -f $HOME/.zshrc.mine ] && source $HOME/.zshrc.mine
