# zshrc 

bindkey -e

setopt auto_cd
setopt auto_pushd
setopt nolistbeep
setopt magic_equal_subst
setopt pushd_ignore_dups
setopt extended_glob
setopt complete_in_word

stty stop undef

# history
HISTFILE=~/.zsh_history
HISTSIZE=100000000
SAVEHIST=100000000
setopt hist_ignore_dups
setopt share_history
setopt hist_ignore_space

# auto complete
autoload -U compinit 
compinit

autoload -U colors
colors

# prompt
PROMPT="[%{${fg[cyan]}%}%n@%m%{${reset_color}%}]$ "
RPROMPT="[%{${fg[cyan]}%}%~%{${reset_color}%}]"

# aliases
alias ls="ls --color=auto"
alias mkdir="mkdir -p"

# cdls
cd() {
    builtin cd "$@" && ls --color=auto
}


#  --- peco ---
#  history
function peco-history-selection() {
    BUFFER=`history -n 1 | tac | awk '!a[$0]++' | peco`
    CURSOR=$#BUFFER
#      zle accept-line
}
zle -N peco-history-selection

function peco-history-set-on-cursol()
{
    peco-history-selection
    zle reset-prompt
}
zle -N peco-history-set-on-cursol

function peco-history-execute()
{
    peco-history-selection
    zle accept-line
}
zle -N peco-history-execute


# process
function peco-kill-process () {
    ps -ef | peco | awk '{ print $2 }' | xargs kill
}

if which peco 2>/dev/null; then
    alias kill="peco-kill-process"
    bindkey '^r' peco-history-execute
    bindkey '^t' peco-history-set-on-cursol
fi


#  load external files
[ -f $HOME/.zshrc.mine ] && source $HOME/.zshrc.mine

# for tmux
if [ -z "$TMUXCLIENT" ]; then
    alias tmux="tmux -2"
else
    alias tmux='tmux -2 -f"$HOME/.tmux.conf.client"'
fi

if which tmux 2>/dev/null; then
    [[ -z "$TMUX" && ! -z "$PS1" ]] && tmux
fi
